#!/bin/bash

[ -z "$1" ] && echo "get yer shiet together dawg :'V" && exit 1;exec sudo ip netns exec $1 sudo -iu $USER bash -ilc "PS1=\"(\[\e[1;31m\]ns=$1\[\e[0m\])\u@\w\$ \" exec bash --norc"

# vim:ts=4:sw=4:et:
